version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/CMPE-273-Team-Project-Quora

hooks:
ApplicationStop:
   - location: ./deploy/stop
     timeout: 60
     runas: root

AfterInstall:
   - location: ./deploy/install-pkg
     timeout: 1200
     runas: root

ApplicationStart:
   - location: ./deploy/start
     timeout: 60
     runas: root

